### ISSUE TITLE
Using BVTKNodes with pip version of the VTK

### ISSUE THREAD

**Issue by piiq** [tkeskita/BVtkNodes#1]
👋 hi
First of all thank you very much for bringing this valuable addon to 2.8. It has potential to provide big opportunities for scientific 3d processing. 

I am trying to setup BVTKNodes in Blender 2.8 on OSX. I didn’t compile vtk, but I have installed vtk 8.2 from pip, using the python that comes with blender. 

Now I can import vtk in blender python console, access classes and do computations. 

The addon does not raise any errors during installation, but I don’t see the node editor. 

Am I missing something in the installation process? Or is there anything special about the python bindings that vtk needs to interact with blender, that makes building from source mandatory?

**Comment by tkeskita** [comment]
Hi @piiq 

what messages do you see in terminal if you start Blender from terminal? It should say 
"Loaded VTK version: 8.2.0" and "VTK base path ..." if it has loaded the add-on successfully.

Can you please describe detailed steps you used to install vtk with pip into Blender? It would be really convenient to use that kind of installation if it works. Thanks!

**Comment by tkeskita** [comment]
FYI Current version is compatible with VTK installed via pip!
