### ISSUE TITLE
Issue installing VTK add-on on Blender 3.6

### ISSUE THREAD

**Issue by lubiole** [tkeskita/BVtkNodes#113]
Hello everyone, i hope this message finds you well,

So i recently heared of the VTK add-on and i'd like to use it to animate a CFD simulation using VTK nodes, but i'm struggling to enable the add on on blender 3D. I tried googling and git-hubing the issue to no avail, this is why i'm looking for help here.

When i try to enable the add on, i get this message error : 
![image](https://github.com/tkeskita/BVtkNodes/assets/166829719/87c076d8-baf3-4c34-adac-7334e81c500a)

If seems like i have an issu with my python version or somehing, but truth to be said, i'm a really newbie regarding all of this

regards,

**Comment by lubiole** [comment]
After a few hours of testing and failing, i finally solved the issue, or should i say that some one on the interted solved it for me.

So basically you need to go into the Python blender folder and install VTK in it, thanks to tkeskita.

`run CMD.EXE as administrator
cd C:\Program Files\Blender Foundation\Blender\2.80\python\bin
python.exe -m ensurepip
python.exe -m pip install vtk`

(https://blenderartists.org/t/bvtknodes-gallery/1161079/8)
![image](https://github.com/tkeskita/BVtkNodes/assets/166829719/32ea5f6e-d482-4c97-aa74-5ff957320dfd)

**Comment by tkeskita** [comment]
Please follow [installation instructions in the docs](https://bvtknodes.readthedocs.io/en/latest/BVTKNodes.html#installation) to avoid this kind of issues.
