### ISSUE TITLE
color_by option in ColorMapper

### ISSUE THREAD

**Issue by vigeesh** [tkeskita/BVtkNodes#14]
Hi @tkeskita 

I'm trying to assign a named array to the `color_by` option in the ColorMapper node within a script.

I can only do it via array numbers like 'P0', 'P1', etc. and not by the array name.

```
>>> colormapper.color_by="P0"
>>> colormapper.color_by="Temperature"
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
TypeError: bpy_struct: item.attr = val: enum "Temperature" not found in ('P0', 'P1', 'P2', 'P3', 'P4', 'P5', 'P6', 'P7', 'P8', 'P9')
```

Is there a way to assign color by the name of the array (like in the Node editor)?
Or, how do I find out the array number (e.g P4 - "Point data [4]: 'Temperature': 5000 - 6000") that correspond to the data I want?

Thank you,
Vigeesh

**Comment by tkeskita** [comment]
Hello @vigeesh 
I guess the behavior here is similar to Paraview (select Nth array instead of a named array).
The list of options is available in the `ColorMapper` node as `color_by` (it's type is `bpy.props.EnumProperty`). Please see `color_arrays()` in `colormap.py`. Perhaps you can search that to find out entry which has correct array name?

**Comment by vigeesh** [comment]
Hi @tkeskita,

Thanks for the pointer.
I was able to get it like this:
```
>>> obj = colormapper.get_input_node('input')[1]
>>> vtkobj = obj.GetProducer().GetOutputDataObject(obj.GetIndex())
>>> pdata  = vtkobj.GetPointData()
>>>'P'+str([pdata.GetArrayName(i) for i in range(pdata.GetNumberOfArrays())].index('Temperature'))
'P4'
```

**Comment by derekeden** [comment]
I was able to do the same like this, which might be a bit more straightforward

```
color_dict = {var[1]:var[0] for var in mapper.color_arrays(surf)}
color_code = color_dict['Surface_elevation']
mapper.color_by = color_code #ordered C0 to Cn where n is nvars in VTK file - C for cell data
```
