### ISSUE TITLE
Upgrade to VTK 9?

### ISSUE THREAD

**Issue by tkeskita** [tkeskita/BVtkNodes#16]
VTK 9.0.1 seems to be available via `pip install vtk`. Is there someone who would like BVTKNodes to be upgraded to VTK 9? What is the reason? I usually hesitate to jump to any new major version at least before x.1 version, and so far 8.1.2 seems to have been working nicely for me at least..

**Comment by vigeesh** [comment]
Hi @tkeskita, I'm using 9.0.1 with the current BVTKNodes. Didn't have any problem's so far.

**Comment by tkeskita** [comment]
OK I've now upgraded BVTKNodes to VTK 9.0.1!
