### ISSUE TITLE
Stack 2D Tiff Images to 3D Model for Volumetric Rendering

### ISSUE THREAD

**Issue by Davincible** [tkeskita/BVtkNodes#19]
Hey there, I am new to Vtk and looking for some guidance.

I am trying to use BVtk to create a 3D model of a microscope image stack of a cell. I tried paraview at first, but ran into some [issues](https://discourse.paraview.org/t/volume-rendering-with-original-image-colors-removing-the-black-fill/5192)

Preview of my images
Original: 
![image](https://user-images.githubusercontent.com/25869544/91470148-a3417000-e894-11ea-8af6-351177603e55.png)

With `convert -alpha copy`:
![image](https://user-images.githubusercontent.com/25869544/91470201-b3594f80-e894-11ea-9874-69d3c446c9df.png)

I am able to load all images, with vtkTIFFReader, and just plugged it into the skull tutorial, but it loads it in in 2D, how can I make it a 3D model? I googled for general vtk pipelines for this, but was not able to recreate it so far. 

My end goal is to keep the color of the original images, and create a photorealistic 3D model of the cell. 

You can view my full data set [here](https://drive.google.com/drive/folders/1cIc1oRddJs3qlc-5R1p55Vqj9rpJXFyX?usp=sharing)

Any help would be greatly appreciated!

**Comment by Davincible** [comment]
After spending a few hours with it I have an idea of what needs to happen, by trying to follow guides on the internet, but I'm not sure which nodes to use exactly to convert the single images into a stack and subsequently a volume. 

The trial and error process is quite tedious as you cant cycle through nodes easily.

**Comment by tkeskita** [comment]
Hi,
I've never done that. Have you found a way to do it in Paraview, or can you share the guide you found? Thanks.

**Comment by Alexxkrehmen** [comment]
Hi,

I had the same issue, and couldn't find a way to directly import a stacked tiff file into BVTK.
I've found a workaround by importing the tiff file into Paraview, and then exporting it as a vtk file.
Then it can be imported into BVTK and converted to an iso surface.

But you want volume rendering.
In this case, I didn't tried the last updates of BVTK allowing, it seems, to do some volume data conversion, but I've found another more DIY solution ;)

1) Save your stacked file a separated images sequence

2) use the "montage" command to merge all of them as a tile map (all image stitched together in a grid manner)
Like this : **montage Image_*.png -tile 16x16 -geometry +0+0 tilesOutput.png**
This will load all "Image_###.png" files and assemble them as a 16x16 tile map saved as "tilesOutput.png"
In my case I had 250 slices, so a 16x16 gives me a maximum of 256
Here we are also limited by the png max width and height, which is 16384 pixels, so I had to downscale all my input pictures to 1024x1024.
If you need a bigger resolution, you will have to crop your input images to isolates areas, and then create a tile map for each area.

3) Once the tile map is ready, it can be imported into blender as a texture input to a node setup I've made, which allows to render it as a volume :)

Here it is :
[volume_stack_demo.blend.zip](https://github.com/tkeskita/BVtkNodes/files/5141364/volume_stack_demo.blend.zip)

**Comment by Davincible** [comment]
@tkeskita 
[This](http://vtk.1045678.n5.nabble.com/How-read-stack-of-TIF-images-td1241362.html) post refers to using vtkImageReader2, which I did try to use, but I  am not sure how to use the output data. Just putting it in a VTK to Blender node seems to give me nothing

[This](https://stackoverflow.com/questions/40241765/new-to-itk-vtk-reading-tiff-files-and-dipslaying-them-either-as-a-volume-or-3d) thread seems to use some ImageStack node, but I couldn't find it in BVtk, and as I don't know C++ I had difficulty understanding the code

[This](https://vtkusers.public.kitware.narkive.com/SQghovoz/can-you-fix-my-very-simple-problem-convert-tiff-series-stack-to-vtk-file-with-python-script) post talks about ImageToStructuredPoints (which I did find a node for in BVtk), and a few other conversion formats.

I have also read somewhere to use an array, and just increment the 'layer' number for each images, such that you basically get a list of images. I did see some ImageStack nodes in the VTK documentation, but not in the BVtk nodes, maybe that could help too

**Comment by Davincible** [comment]
@Alexxkrehmen Sounds interesting! I'll have a look at that, thanks.

**Comment by tkeskita** [comment]
Hi,
thanks for links! It looks like you need to [add Custom Code](https://bvtknodes.readthedocs.io/en/latest/BVTKNodes.html#properties) to the *vtkTIFFReader* node to make it do the stacking (see image below). `FilePattern` must have complete absolute path with correct number definition string in the end to read the separate tiff files (I didn't try to read in your massive 3D data file). In this example I tried to read in only 5 test slices, so modify `SetDataExtent` in the Custom Code for your case. *vtkArrayCalculator* here only extracts first of char4 values to show it's working.

![Screenshot_2020-08-28_17-44-02](https://user-images.githubusercontent.com/38000348/91581888-c123d900-e957-11ea-959c-91499bf40101.png)

Now, the big problem for you is how do you intend to process and visualize that massive data? Your data would likely be ideal for volumetric rendering, but to do that you need to either 1.) skip BVTKNodes and convert your data to OpenVDB format with a custom C++ program (see [here](https://blenderartists.org/t/bvtknodes-gallery/1161079/47) and [here](https://discourse.vtk.org/t/bvtknodes-photorealistic-rendering-of-vtk-data-in-blender/3268/22)) or 2.) (if you are expert) build a custom Blender to use [VTK To Blender Volume](https://bvtknodes.readthedocs.io/en/latest/BVTKNodes.html#vtktoblendervolume).

**Comment by Davincible** [comment]
@tkeskita Thanks for the suggestions! I will try that out. Although I do know Python and not C++, I can compile the C++ script and figure out how to get that to work. Compiling a custom blender should be possible too, I read you wrote a guide for Linux so that's perfect.

**Comment by Davincible** [comment]
![image](https://user-images.githubusercontent.com/25869544/91638650-520abb00-ea11-11ea-8c72-2a89f2c2e39d.png)
Did you use a specific version?
I have:
Blender 2.83
vtk==8.1.2 (installed in blender's python env)
latest BVtk

**Comment by Davincible** [comment]
@tkeskita Update:
I recreated your node setup above, minus the coloring, and initially when I tried to load in my whole dataset Blender just crashed due to memory limitations. After enabling a 16gb swap file and downsampling to 256x256 to I did manage to load it in. Which resulted in a cube: 
![image](https://user-images.githubusercontent.com/25869544/91913463-fc0a7180-ecb5-11ea-8383-4d94217741bf.png)

After adding a contour filter I did get some results, although not great:
![image](https://user-images.githubusercontent.com/25869544/91913782-be5a1880-ecb6-11ea-8818-658d5a234212.png)

Another thing I tried was exporting the dataset I loaded into Paraview as .vtk, and loading that into BVtk, and with a contour filter, I did get an outline of the cell:
![image](https://user-images.githubusercontent.com/25869544/91914319-0fb6d780-ecb8-11ea-8d19-e6eeb8790f58.png)

Understandably, the outline doesn't contain the original colors. So the best approach here I think is to create the custom build of Blender to use the volume rendering node to convert this .vtk import format. Do you have a guide or some steps I can follow to create a build for Ubuntu?

**Comment by Davincible** [comment]
@Alexxkrehmen How do I use your pipeline exactly? I created the map, and changed the file:
![image](https://user-images.githubusercontent.com/25869544/91918375-0121ed80-ecc3-11ea-9606-ad6919a30131.png)
Im seeing a box now

**Comment by Alexxkrehmen** [comment]
This is for volume rendering... so you have to render it ;)

You can use Eevee for quick preview and Cycles for final rendering.
You may need to change some clipping settings to get a proper eevee rendering. Let me know if you have any issue with it.
Else using Cycles for preview is also fine, just a little slower, depending on your gpu.

**Comment by Alexxkrehmen** [comment]
This is for volume rendering... so you have to render it ;)

You can use Eevee for quick preview and Cycles for final rendering.
You may need to change some clipping settings to get a proper eevee rendering. Let me know if you have any issue with it.
Else using Cycles for preview is also fine, just a little slower, depending on your gpu.

**Comment by tkeskita** [comment]
@Davincible 

Note: contour filter should go before geometry filter, unless you want to contour the boundaries only.

Sorry, I have not written instructions for building Blender with pyopenvdb enabled, as [there seems not to be much interest](https://blenderartists.org/t/bvtknodes-gallery/1161079/52) (I've tried to [redirect people there in the docs](https://bvtknodes.readthedocs.io/en/latest/BVTKNodes.html#vtk-to-blender-volume-openvdb)).

Most of VTK Python uses a single thread. There might be parallel processing possibilities similar to Paraview's pvserver, but I haven't checked those. If you can make it parallel in VTK Python, you can likely make it parallel in BVTKNodes.

**Comment by Davincible** [comment]
@Alexxkrehmen 
You're totally right lol. I'm new to blender, so need some pointers here and there, but did some research and managed to get some results! : 
![image](https://user-images.githubusercontent.com/25869544/92007849-b9dd4080-ed46-11ea-9626-7475a91042c8.png)

I noticed (strangely) that when I do this with my images without background (convert -alpha copy, see my first post) I get the box, while if I do it with the regular images with the black background I get the result above. For both some clipping/ thresholding would be nice. How do you apply that? I looked around the settings and on google but the only clipping I could find was slicing the whole object in two.

Also, how would you do this with a larger stack? my images are 1080px, so the width fits, but I would like to have more than 256 slices in the model.

Thanks a lot for all the help, its appreciated

**Comment by Alexxkrehmen** [comment]
Hi,

I'm on vacation right now so I've not access to my source files. But here are some tips :

- if you have an alpha channel, then you can plug the "Alpha" output of the Image node in the Multiply node linked to the density input of the Volume node.
The alpha will then be used to drive the density of the volume.

- as it is now, the luminosity of the image is used as density, so black = 0 density and white = 1 (then it is multiplied by 1000, but you can tweak this value)

- for a larger dataset, you will have to split it in multiple tile maps, I've already managed to get it working, but I don't have any sample here.

- for the clipping, you can used Signed Distance Fields to define some kind of substract or intersect volumes, and even animated them... Once again I've this running, but not here right now ;)

I'll post everything next week, when I'll be back home.

**Comment by Davincible** [comment]
Hi @Alexxkrehmen ,

Enjoy your vacation! I'm excited to see what you'll have when you're back. 
In the meantime, I have done some research into rendering, and Eevee vs Cycles.

I managed to solve my thresholding problem with a very simple math node set to "greater than 0.010", this filters out all the noise.

However, now my next problem is/was banding on the rendering. I noticed online that it is more common.
Notice the banding in the screenshot below:

Default settings; Volume Step Rate: 1.0, Multiply: 1000
![image](https://user-images.githubusercontent.com/25869544/92267882-b7631e00-eee1-11ea-988b-9624220cac92.png)

After a bunch of trail and error, I managed to mitigate the banding issue by changing the "Step Rate" In Material Properties > Volume (as you can see below). However, compared to the previous render, this one looks much less clean, with noise around the model. Do you know how I can fix that?

Volume Step Rate: 0.1, Multiply: 100
![image](https://user-images.githubusercontent.com/25869544/92268322-71f32080-eee2-11ea-87c9-4fefa237d468.png)

I also managed to get Eevee working. But I'm not sure it's any better. The "start" "end" settings also confuse me, as they both control the rendering distance, as well as quality. Although I'm not too worried about that

Enjoy your holiday

**Comment by Alexxkrehmen** [comment]
@Davincible 

Hi, some quick answers :

With Cycles : lower Step Rate = finer sampling = better quality = longer render time.
To reduce the noise, you have to raise the overall sampling value of the render engine. I can see in your screenshots that you are using 64 samples in the final render. Try with a bigger value.
Of course this will also result in longer render times...

For Eevee, the Start and End parameters are defining the begin and end distance from the camera to render the volume.
Eevee uses some sort of slicing parrallel to the camera to render volume, that's why you've noticed that both the area and quality are affected by these two parameters.
If the distance between Start and End is low, you'll get all slices condensed in a narrower area, so a better quality.

Anyway, Cycles will always gives a finer result... with a slower rendering.

More to come next week ;)

**Comment by Alexxkrehmen** [comment]
@Davincible 

I'm back !

So here is my other demo file, with multiple stacks and clipping shapes.
[monkey_volume_demo.blend.zip](https://github.com/tkeskita/BVtkNodes/files/5183555/monkey_volume_demo.blend.zip)

I've created 100 slices stack from a Suzanne object, and clipped it with a Sphere, a Box and a Plane.

In the shader graph you will find multiples frames.

- Single Tilemap : this one is the same as the previous sample file
- 4 tilemaps : this one has 4 textures inputs added together. To test it, you must plug the output of this addition in place of the single tilemap
- 2 tilemaps + Mirror : this one is just an example on how to use only 2 stacks instead of 4 when the object is symmetrical

- Filter low value : remove the low noise.

- Clip Sphere / Box / Plane : these 3 setups are defining [signed distance fields](https://www.ronja-tutorials.com/2018/11/10/2d-sdf-basics.html) used to do volumetric boolean operations.

For the clipping plane, I've added a Vector rotate node, to try simplify the orientation of the plane ... Let me know if you need more explanations. Else you can just modify the "Direction" vector, which must have at least one value above zero.

- Boolean operations : here all values must be multiplied to give the final result.

I've also added a little example to make color volume from a sphere.

To generate the multiple tilemaps, I've used the convert command line :
My original sequence is labelled as "monkey_000.png", size is 1024x1024

To split it in four, I've used theses command lines :

convert -crop 512x512+0+0 m*.png tiles_A/monkey_A_%03d.png
convert -crop 512x512+512+0 m*.png tiles_B/monkey_B_%03d.png 
convert -crop 512x512+0+512 m*.png tiles_C/monkey_C_%03d.png
convert -crop 512x512+512+512 m*.png tiles_D/monkey_D_%03d.png

Each cropped sequence will be saved in a different folder, and with a different name. the %03d par in the name is used to generate de number sequence with padding zeros (this is important to get them properly ordered when assembled in the tilemap).

Then I've used the montage command to merge each sequence in a single tilemap

montage m*.png -tile 16x16 -geometry +0+0 tiles.png

It gives me a tile maps of 16 columns and 7 rows. That's what you can see in the nodes.

Let me know if you need more explanations ;)

**Comment by Davincible** [comment]
Hi @Alexxkrehmen, 

Thanks a lot for your info, it has been really useful. I will look at implementing your last post this week, so far I have been busy researching how Blender works with rendering. After a few hours of camera frustrations I managed to create a few good renders:

![image](https://user-images.githubusercontent.com/25869544/92446793-a3a40a00-f1b6-11ea-91b2-6614c22888b3.png)


![image](https://user-images.githubusercontent.com/25869544/92446726-896a2c00-f1b6-11ea-9ce1-323b20e67234.png)

**Comment by Davincible** [comment]
Hi @Alexxkrehmen , 

I haven't yet gotten to your latest examples, working on creating bigger animations first. 

But I noticed that when rendering an animation, the tile map has to be loaded in for every frame in the animation, which takes around 10 seconds. In a quick and dirty sample animation, this is longer than the actual frame render time. Is there a way to cache the tile map, so it doesn't have to be reloaded on every frame?

**Comment by Alexxkrehmen** [comment]
Hi ! @Davincible 

Glad to see you are progressing :)
Let me know if you need help for the clipping operations !

**Comment by tkeskita** [comment]
Hey people, nice work! If you get renderings done, please consider posting them to https://blenderartists.org/t/bvtknodes-gallery/1161079

**Comment by Davincible** [comment]
@Alexxkrehmen So I'm going through your Suzanne blend file now, and just when I thought I was starting to get good at it I get massively confused hahah. 

So my questions:
    1. I'm trying to understand the flow of the nodes (what does what), but I can't seem to figure out. What is input and output, what manipulates what? Both the tilemap contraptions go to "Add4", but I can't find that back anywhere else.
    2. Why did you divide the 1024 into 4, because the 1024 fits inside the tile map right. So why not stack multiple tilemaps vertically?
   3. I tried stacking two tile maps vertically, by just duplicating the object from the first example, but as they're linked that doesn't work. Should I split those horizontally, or can I somehow stack them vertically?

**Comment by Davincible** [comment]
@Alexxkrehmen I understand how the tile map works now, converted to a 32x32 map so I could fit 388 slices. However, the green "Add" node which adds the four different tile maps removes the color. If plug the raw output of the tile map into the color input, I do get color. Not sure how to fix that yet

**Comment by Alexxkrehmen** [comment]
Yes, my Add4 only works with a single float value.

The problem I can see in your setup is the output (Sum) is a single float value (gray dot) but it should be a color output (yellow dot)
To get it, simply plug the Image output of your last Combine RGB node into the hollow dot of the Group Output, in order to generate a new output dot with the correct output format.
Then you should remove the previous one.

**Comment by Davincible** [comment]
@Alexxkrehmen Your suggestion did work. I had to reconfigure the input and output nodes to be images, then the volume was colored. However, I also found out that your initial assumption about png only being able to handle 16k x 16k pixels was false. As the only max is the 32 signed bit max value. I could create a single tile map of my 388 1024x1024 slices, which I could just load into the first model. That creates a significantly easier workflow

**Comment by Alexxkrehmen** [comment]
The 16k x 16k limitation was effective on my computer, at least.
I don't know how to go beyond that, maybe I have to configure something... I'm glad you've been able to workaround this !

**Comment by Davincible** [comment]
@Alexxkrehmen I'm not sure, I haven't changed any configs. My current workflow is basically taking the ceil of sqrt(stack_size) as montage tile size, which has no limit. I'm using PopOS (Ubuntu basically), maybe if you're using windows you have that limit.

**Comment by Alexxkrehmen** [comment]
@Davincible Linux Mint here... But I've seen there are some config files for the montage command, where I could change some values. I'll give it a try.

**Comment by tkeskita** [comment]
FYI there is now [VTK To OpenVDB Exporter](https://bvtknodes.readthedocs.io/en/latest/BVTKNodes.html#vtk-to-openvdb-exporter) node available, but you need external `pyopenvdb` to use that to convert image data to OpenVDB. For linux distros there should be package like `python3-openvdb` for Ubuntu and derivatives available for that.

**Comment by Alexxkrehmen** [comment]
@Davincible Yo !

I have a new simpler solution ! Using UDIMs :)

Use this setup as texture coordinates input in a UDIM images list of the slices :

![image](https://user-images.githubusercontent.com/12670889/197387155-5d45ad5a-187d-44e6-8c6e-440e587ca582.png)

![image](https://user-images.githubusercontent.com/12670889/197387183-2384aef8-a500-49a9-b88f-3083bcc37951.png)

And you'll get the right result, without needing to make a big tile map :)

**Comment by Davincible** [comment]
@Alexxkrehmen that's looks a alot simpler!

I've since completed the project I was working on, but thank you for thinking of me :)
