### ISSUE TITLE
Scripting with BVtkNodes

### ISSUE THREAD

**Issue by vigeesh** [tkeskita/BVtkNodes#2]
First of all, 
@simboden - thanks for bringing this Addon to Blender, and
@tkeskita - thanks for getting it on 2.80
Everything works fine with the BVTK Node Tree Editor and I get what I want.
Recently, I started scripting with it and I'm having some issues. I thought you might be able to help me out.

With python, everything seems to work as expected, but the scene is not getting updated until the script has finished running.

For instance, here is a minimal reprex:
```
import bpy

#Add the BVtkNodes
bvtkn = bpy.data.node_groups.new('NodeTree',type='BVTK_NodeTreeType')

# Cache the Nodes and Links
nodes = bpy.data.node_groups["NodeTree"].nodes 
links = bpy.data.node_groups["NodeTree"].links

# Create the Reader
reader = bvtkn.nodes.new(type="VTKXMLImageDataReaderType")
reader.m_FileName = "examples_data/head.vti"

# Create the Contour Filter
contr_filter = nodes.new(type="VTKContourFilterType")

# Add a contour value
item = contr_filter.m_ContourValues.add()
item.value = 66.

# VTK To Blender
vtk_to_blend = nodes.new(type="BVTK_Node_VTKToBlenderType")

# Create the links
links.new(reader.outputs["output"], contr_filter.inputs['input'])
links.new(contr_filter.outputs['output'], vtk_to_blend.inputs['input'])

# Update the BVtkNode
bpy.ops.node.bvtk_auto_update_scan(
    node_name="VTK To Blender",
    tree_name="NodeTree")

# Print the list of objects in the scene
print(bpy.data.objects[:])

```
When I run the above script, the output is, 
```
[bpy.data.objects['Camera'], bpy.data.objects['Cube'], bpy.data.objects['Light']]
```
The scene gets updated with the new object only after this.

The problem is that the object does not exist until the script has completed executing. So, I am unable to call the object within the script. I even tried to add in a time delay to wait for the BVtkNodes.

What am I doing wrong here?

**Comment by tkeskita** [comment]
Hello @vigeesh ,

nice example of scripting BVTKNodes! You are right that the reason you don't see object named 'mesh' is because bvtk_auto_update_scan returns before nodetree finishes execution. Instead of auto update scan, please try to use bvtk_node_update with use_queue as False, like so:

```
node = vtk_to_blend
node_path = 'bpy.data.node_groups['+repr(node.id_data.name)+'].nodes['+repr(node.name)+']'
bpy.ops.node.bvtk_node_update(node_path=node_path, use_queue=False)
```

BR,
Tuomo

**Comment by vigeesh** [comment]
Thank you very much. It works like a charm.
