### ISSUE TITLE
No custom Code available for 

### ISSUE THREAD

**Issue by thomas-grand** [tkeskita/BVtkNodes#22]
Hi,

many thanks for this Blender Addon.
While trying to plot a glyph vector following the tutorial, I tried to select the correct vector by removing all unused fields. However, the nodes vtkPassArrays and vtkAssignAttribute did not have a properties field "Custom Code" to allow this, as mentioned in the tutorial (see screenshot). 
![bvtk_no_custom_code](https://user-images.githubusercontent.com/34158449/92509541-adeff380-f20a-11ea-8661-dfc445c81f6f.png)

OS: Windows & Linux
Blender version: 2.83/2.9
VTK version: 8.1.2

**Comment by tkeskita** [comment]
Hi, please try Edit Custom Code in properties tab, edit code in Blender Text Editor, then Save Custom Code. Looks like people don't find out how to use it easily, I'll try to improve docs. It's now mentioned in tabs docs in https://bvtknodes.readthedocs.io/en/latest/BVTKNodes.html

**Comment by thomas-grand** [comment]
Thanks! That solved the problem with the custom code. 
I was still unable to generate a 3D arrow plot from my vector data in the file. Everything simply points in the global X-direction, with and without the ArrayCalculator. Any idea what I got wrong? Also curious if there is any way to show the actual VTK error message
![vtk_error_code](https://user-images.githubusercontent.com/34158449/92766817-dc023e80-f396-11ea-9335-8daf810cb49b.png)
![bvtk_quiver](https://user-images.githubusercontent.com/34158449/92766821-dc9ad500-f396-11ea-8aa9-948ceff91449.png)

**Comment by tkeskita** [comment]
Hi,

you are missing vtkAssignAttribute before vtkArrayCalculator, see https://bvtknodes.readthedocs.io/en/latest/ug_nodes.html#contours

Those VTK pipeline errors occur on first run when not all of the VTK objects are up-to-date. When you update VTK To Blender node they should not appear again, unless there is error in the node tree. Some error messages are shown in terminal where Blender is started, if Python Logging module is configured correctly (see comments on top of https://github.com/tkeskita/BVtkNodes/blob/master/core.py)

**Comment by thomas-grand** [comment]
Thanks, that solved my problem.
