### ISSUE TITLE
Ensight to BVtkNodes

### ISSUE THREAD

**Issue by CFDTom** [tkeskita/BVtkNodes#33]
Hello everyone,
I’m currently using CFX from Ansys where is the option to export results to Ensight Gold. I already use this method before through Paraview and it works OK, but when I tried to import the same results directly to Blender via BVTKNodes, everythings seemed fine until I took a look at velocity. It seem that the algorythm used in BVTKNodes doesn’t sort the cell or node data correctly (attached pic.). I don’t know what I’m doing wrong. Anyone who did experience something similar?
Also, I'm new to BVtkNodes, so maybe I forgot to do something.

Thank you for you help.
PS: Other variables (like Total Pressure) seems fine to me which is even more odd.

![screen](https://user-images.githubusercontent.com/79528420/108866331-657b9500-75f4-11eb-86ad-e3575b88908c.PNG)

**Comment by renehommel** [comment]
Dear all 

I faced a similar issue a while ago. Your extracted Velocity field seem to be of type Point Data. Your screenshot is bit blurry in my eyes, can’t read the nodes clearly. 

There could be 2 issues:

1) Cell vs Point data. Although I believe this is not the reason. Check if Pressure is on Cell data. The little icon left of the DropDown variable selection shows the data type: point data have this little dot, cell data show a square. Maybe there’s a bit different behavior when displaying point data.

2) The more likely reason: the CFX/Ensight Velocity field comes as tensor with the three components u,v,w, means it's required to calculate the magnitude U by using the vtkCalculator and display that.

Hope that helps

Bests, René

**Comment by CFDTom** [comment]
Hi René,
Thank you for your quick reply. 
Ad 1) Yes, all variables should be in point type data according to your description of the icon. It make sense because CFX is node based solver.

Ad 2) Yes you are right, velocity and other vector field data are as tensors, but three components are calculated in post-processing (don't know how yet), this means that the result data file doesn't include components. Is there any chance how to convert it in BVtkNodes so the contours will make sense. Paraview does this automatically.

Also here is the picture of my nodes, hope it's a bit more clean to see what is what.

Regards, Tom
![screen2](https://user-images.githubusercontent.com/79528420/108877564-a4631800-75ff-11eb-8036-bf9a33d07bfb.PNG)

**Comment by tkeskita** [comment]
Hi,
contents of the Info node would be helpful here. If/when `Velocity` is not a scalar, then you're getting color by the first Velocity component in that setup. See [here](https://bvtknodes.readthedocs.io/en/latest/ug_nodes.html#field-data-calculations) how to calculate velocity magnitude. Also, without specifying an active attribute before vtkStreamTracer (e.g. by vtkAssignAttribute, see [here](https://bvtknodes.readthedocs.io/en/latest/ug_nodes.html#stream-tracers)) you may be using a wrong vector field for tracers.

**Comment by CFDTom** [comment]
Hi,
thank you for the info. It make sense. I tried this but it seems it doesn't work. Maybe I should do something more with my data.
Here is my nodes with a little more simple case to avoid the Streams problem for the begining.

Thank you for your help
Tom

![screen3](https://user-images.githubusercontent.com/79528420/109038881-7dbee300-76cc-11eb-9ab4-6f1e50a8111d.PNG)
Also, here is an error log from info node that comes afte vtkPassArrayes node.
![screen4](https://user-images.githubusercontent.com/79528420/109038885-7ef01000-76cc-11eb-8ef1-eb9d577c8441.PNG)

**Comment by renehommel** [comment]
Hi

My Ensight workflow looks as follows. My calculator code needed to be different from what I’ve seen at the provided BVTK examples. Sometimes inspecting the VTK documentation provides the ultimate hint

Bests, René

**Comment by renehommel** [comment]
here my screenshot
<img width="2010" alt="ensightWorkflow" src="https://user-images.githubusercontent.com/31559173/109057350-ed8b9880-76e1-11eb-8ef5-90b832352dc3.png">

**Comment by CFDTom** [comment]
Hi René,
thanks a lot for your screenshot. It is very helpful to understand how it works. I tried to do it the same way like you did but unfortunately no success. I also tried to export it to Ensight Gold Binary. This worked same way as nonbinary but no success with vtkPassArray. I also tried to convert points data to cell data via vtkPointDataToCellData to ensure this is not the problem. This conversion doesn't work either and vtkPassArray shows the same error. So maybe there is something I have to do with my data. I guess my data are OK according to Paraview.

Regards, Tom

**Comment by tkeskita** [comment]
The vtkInformation error appears when the pipeline is not updated. I noticed you did't have a VTK To Blender Mesh node at the end of your pipeline. Add one and run Update on it to refresh the preceding node tree. If that doesn't help can you please share a small example data?

**Comment by CFDTom** [comment]
Hi,
thanks a lot. Now I feel like total amateur lol :D That solved the problem. I thought that the info node will update it by itself.
The only thing is that the boundary velocity should be zero, but that's the different problem.
VTK tools inside Blender is really amazing thing.

Thanks a lot both of you for your help.
Regards, Tom
![screen5](https://user-images.githubusercontent.com/79528420/109168718-5f65ef80-777f-11eb-8448-aaca8f5d3381.PNG)
