### ISSUE TITLE
vtkPassArray producing vtkCompositeDataPipeline error

### ISSUE THREAD

**Issue by NickGeneva** [tkeskita/BVtkNodes#34]
Howdy,

I am just starting to get a feel for this add-on (new to blender) and I am having some trouble replicating some of your lovely examples on the [blender forum](https://blenderartists.org/t/bvtknodes-gallery/1161079/22).

I am reading in a particle file from [DualSPhysics](https://github.com/DualSPHysics/DualSPHysics) simulator on a different machine (which I believe was also used in the example based on file names) and I am able to import the file fine. However I am running into some issues where my custom code in nodes such as vtkPassArray or vtkArrayCalculator which does not seem to run and produces an error. See example below.

Without the vtkPassArray node I can continue to create 3D glyphs, colormap, etc. just fine. I tried other [vtkDataObject formats](https://vtk.org/doc/nightly/html/classvtkDataObject.html#a75b13d501194938772601cb0a3385f20) without luck.

Any thoughts? Am I just missing something silly? Many thanks!

A minimal working example of this follows:
![image](https://user-images.githubusercontent.com/5533524/109373629-04ff8880-787e-11eb-9604-e39bcf85c654.png)

![image](https://user-images.githubusercontent.com/5533524/109374120-02526280-7881-11eb-94d6-b839514321b1.png)

OS: Windows
Blender Version: 2.92 (installed via steam)
VTK version: 8.1.2

Current installed python modules:
![image](https://user-images.githubusercontent.com/5533524/109374257-e7ccb900-7881-11eb-805c-8d2c132880c0.png)

**===Update===**
Seems I can force the nodes to execute correctly by putting in the VTK to Blender node. I still get a bunch of those Datapipeline errors related to the vtkPassArrays node but the output of the info nodes seems correct. Also it does add the object to the scene. Still seeing if I can get the calculator working despite these errors. Maybe has to do with the vtk file (inconsistent version maybe)...

![image](https://user-images.githubusercontent.com/5533524/109375916-9545c980-788e-11eb-83f8-12f8e4909ed0.png)

**Comment by tkeskita** [comment]
Hi, yes it should work and not produce new errors when you run Update on the final VTK To Blender (Mesh) node. I'd better add a notice about those "bogus" error messages to docs, since people get confused about them a lot..

**Comment by NickGeneva** [comment]
Thanks for the quick response @tkeskita appreciate it.

An update. I've done some more testing/debugging this morning to try to figure out whats causing this to complain. Similar to forcing the vtkPassArrays with vtk to Blender, it seems I can also force it to execute by *reloading scripts* then updating the info module after it.

So after reload scripts press:
![image](https://user-images.githubusercontent.com/5533524/109395938-18056d80-78fd-11eb-8a09-04803a9baa6a.png)
does produce
![image](https://user-images.githubusercontent.com/5533524/109395948-2489c600-78fd-11eb-8178-126ab7e91cef.png)

I do still get those annoying errors, but I get through the node. Also note **If I click on the update on first info node, I lose the ability to update the last one and have to reload scripts.**

I've also been doing some testing in just python to see if its the VTK package/file/whatever causing the issues. I was able to write this simple (equivalent) script that works fine using the blender python.exe.
```python
import vtk
from vtk import vtkPolyDataReader

reader = vtkPolyDataReader()
reader.SetFileName(r"path_to_file\PartFluid_0050.vtk")
reader.ReadAllVectorsOn()
reader.ReadAllScalarsOn()
reader.Update()

pa = vtk.vtkPassArrays()
pa.SetInputConnection(reader.GetOutputPort())
pa.AddArray(vtk.vtkDataObject.POINT, 'Vel')
pa.Update()

print(pa.GetOutput())
```
This yields an expected output that is just the velocity field.

I am still trying to get a feel for the BVTK source code, to see if I can pinpoint the location of the executed command that causes this error to rise in VTK. This is very odd and I am not sure what the deal is since just using Python works without errors... will update in near future.

**Comment by NickGeneva** [comment]
PR #35 tries to fix the progressive info update issue I having, still get the pipeline errors... so not closing this issue yet.

**Comment by tkeskita** [comment]
Nice fix for the Info node, thanks!
I've added Error Messages section to docs. I think the VTK pipeline errors are raised when VTK input is missing before first update round (no VTK objects yet created).

**Comment by NickGeneva** [comment]
@tkeskita thanks for approving the PR....

Okay so after another few hours of debugging I believe I have finally found the trouble spot. After a lot of tracing (fyi to trace these vtk error you need to sleep the code pretty frequently to allow the blender console and vtklog to sync otherwise the vtk log tends to get ahead of the blender console output.) I found it was [UpdateObj](https://github.com/tkeskita/BVtkNodes/blob/master/update.py#L19).

The problem is partially related to the order of the apply_properties and apply_inputs... essentially the vtk's properties are applied first (makes sense) then the input connections are hooked up and the vtk module can execute.

I finally noticed that on the custom [code wrapper](https://github.com/tkeskita/BVtkNodes/blob/master/core.py#L217), an update call to the node is present.
![image](https://user-images.githubusercontent.com/5533524/109427915-8829f700-79c2-11eb-96f7-646ce6a26978.png)
Given that this is before the input connections are hooked up, vtk doesnt know how to update the object yet and spits out an information error.

**Removing this update call** and just using the update call in [UpdateObj](https://github.com/tkeskita/BVtkNodes/blob/master/update.py#L27) handle the update after properties and inputs have been applied seems work nicely for my little test case (*Ignore the colors things got messed up during crashes*).
![image](https://user-images.githubusercontent.com/5533524/109427970-d7702780-79c2-11eb-9a52-910e737fdb22.png)
with a clean vtk log.

**Note** I created PR #36  but I am presently unsure if other methods rely on this wrapper to update, something to verify. An *alternative* fix would be to swap the apply inputs/apply prop in updateobj, but imo the proper way show be to not have the apply_prop update the vtk object and use the check in UpdateObj to handle it. 

(This also get my vtkArrayCalculator working as expected also.)

**Comment by NickGeneva** [comment]
Update after further testing found that the issue still persists on initialization... using the fix in PR 36 does fix part of the bug through with it still popping up during re-runs.

**Comment by NickGeneva** [comment]
Created PR #38. I hope this time both fixes will get the job done safely. Tested and working for the following example with clean vtk log even after reloading addons, re-opening file, and re-starting Blender.
![image](https://user-images.githubusercontent.com/5533524/109680987-04e7dd00-7b4b-11eb-8f7f-d1e2e6fda0f6.png)

Also tested on full render example
![image](https://user-images.githubusercontent.com/5533524/109681437-76279000-7b4b-11eb-9891-232baf81092d.png)


Explanation is in PR details.

ps. After debugging, I think the way the vtk_cache works can be streamlined a little/ improve... but this is unrelated to the issue. May work on this and PR in the future.

**Comment by NickGeneva** [comment]
PR #38 merged. Closing issue, can reopen if this error arises again.
