### ISSUE TITLE
CountourFilter contour value keyframing does not work

### ISSUE THREAD

**Issue by tkeskita** [tkeskita/BVtkNodes#53]
Looks like the Contour values in vtkContourFilter can't be keyframed for animation (using Global Timekeeper Node implemented in #48 ).

**Comment by thomgrand** [comment]
I looked into the issue some time ago. The main problem is that contour values are not standard properties, but a CollectionProperty with custom BVTK_PG_ValueSettings. Such a value setting is inserted/deleted into the collection, when adding/removing contour values. The keyframing of this custom property already fails on the Blender level, irrespective of the Global Timekeeper Node.
BVTK_ContourHelper would need to dynamically create properties for each contour value for this to work.

**Comment by tkeskita** [comment]
Thanks for info, I was afraid there's an issue. Idea for future: try to add one or few hard-coded FloatProperty contour values that can be animated.

**Comment by tkeskita** [comment]
> Idea for future: try to add one or few hard-coded FloatProperty contour values that can be animated.

Done like so for now (Single Value).
