### ISSUE TITLE
Need some clarifications I can't find in documentation/example

### ISSUE THREAD

**Issue by derekeden** [tkeskita/BVtkNodes#62]
Hi,

First I just wanted to say thank you SO much for maintaining this repo. As someone who's been dabbling with Blender for a couple years, but am used to doing model renderings in Paraview, Python and various other software, this is absolutely amazing. 

I was hoping you could clarify a couple things so I can understand how to use a couple of the VTK functions in Blender.  Specfically, I am trying to figure out :

vtkClipDataSet and vtkWarpScalar

--------------------------------------------------------------------------------------
For clipping, I'm just trying to figure out what I actually need to pass in here. What is ClipFunction supposed to be or are you able to give me an example?

This is what my nodes look like now:

![image](https://user-images.githubusercontent.com/36650862/125542140-71f502a7-770f-42ba-8db7-a164a33fd80f.png)

I get an error that it can't do the clip without a clipping function.

My aim is to do a clip by scalar, using a function like:

Variable_Data >= -999

like in paraview:

![image](https://user-images.githubusercontent.com/36650862/125543167-e667af5e-af51-4d86-8949-f16302189dab.png)

Can you give me an idea how to do this?
--------------------------------------------------------------------------------------
For warp scalar, I am trying to warp the z axis of the surface by the scalar value. Like this in paraview:

![image](https://user-images.githubusercontent.com/36650862/125543387-03baf053-7399-4080-a0d6-589a6184820c.png)

I've tried a couple different things with the BVTK node and couldnt get it to work..

![image](https://user-images.githubusercontent.com/36650862/125543424-773c8853-34db-4ef3-9a30-720befae04cb.png)

Are you able to give me an example how I can warp the surface by a scalar?

I tried using Custom Code by adding:

AddArray(vtk.vtkDataObject.POINT, "Surface_elevation")

and in vtkPassArrays.. also tried using a vtkArrayCalculator..

I'm honestly not that familiar with VTK itself and really don't know what I'm supposed to be giving it.

Can you point me in the right direction?
---------------------------------------------------------------------------------------

FYI I know I need to connect these to a to Blender node to create the blender mesh.. I've just screenshotted the minimum to show you what I'm trying to do.

**Comment by derekeden** [comment]
I was able to figure out the vtkWarpScalar after a couple hours of going in circles :) probably not hard if I knew what I was doing..

![image](https://user-images.githubusercontent.com/36650862/125558681-4933b144-c042-433e-bb05-0543c9bfdbbb.png)
![image](https://user-images.githubusercontent.com/36650862/125558700-95d23761-5fae-4b09-8767-76f18e4a42e7.png)

now to work on the clipping..

**Comment by brioglade** [comment]
Could you please send the data file that I want to exercise this example you had done.Thank you very much.

**Comment by derekeden** [comment]
[dfs2output.vtk.005.txt](https://github.com/tkeskita/BVtkNodes/files/6825071/dfs2output.vtk.005.txt)

just remove the .txt from the file name, github wouldn't let me upload the file with the existing extension

**Comment by brioglade** [comment]
Thank you @derekeden

**Comment by derekeden** [comment]
If you figure out how to do clip by scalar please let me know

**Comment by brioglade** [comment]
OK.😃

**Comment by brioglade** [comment]
hi, why I can't get the rendering image since there is no error?
[image: image.png]

**Comment by derekeden** [comment]
I can't see the image you posted can you try again

**Comment by brioglade** [comment]
[image: image.png]

**Comment by brioglade** [comment]
hi,
https://drive.google.com/file/d/1WPfs-Mz5P3YvKvOrbiVdodj2RqImjQda/view?usp=sharing
Could you please have a see?I can't get the rendering image with vtknodes.
Thank you very much.

**Comment by tkeskita** [comment]
Quick comments: please use github web interface, it works better. For clipping see [this example in the docs](https://bvtknodes.readthedocs.io/en/latest/ug_nodes.html#iso-surface).

**Comment by brioglade** [comment]
Thank you@Tuomo
How to get the vtkUnstructuredgridoutlinefilter?

**Comment by derekeden** [comment]
> Quick comments: please use github web interface, it works better. For clipping see [this example in the docs](https://bvtknodes.readthedocs.io/en/latest/ug_nodes.html#iso-surface).

**Comment by derekeden** [comment]
sorry accidentally clicked close so had to reopen... I will test this out on both surface and volume data shortly and let you know how it works out for me... my concern is that if I use a isosurface, it will create a hollow shell with just 1 contour value. In paraview when you clip by scalar, it's like clipping everything above/below a certain value (as opposed to just one value)...and particularly for volume data, after clipping by scalar there is still internal data in the clipped mesh (i.e. you could slice the clipped mesh)..

I could be totally confusing myself, and will let you know once I've tried with some real data

**Comment by tkeskita** [comment]
@derekeden if you need to exclude some cells, you can try `vtkThreshold`.

@brioglade not sure what you mean? Please check [the examples in the docs](https://bvtknodes.readthedocs.io/en/latest/ug_nodes.html). Also please use github web interface when replying.
