### ISSUE TITLE
i need a vti to openvdb/json example

### ISSUE THREAD

**Issue by Molers** [tkeskita/BVtkNodes#66]
hi,I I read a few issues,But I still don't know how to do it,i want to convert vti to vdb ,use you  
python3 convert_to_vdb.py volume_00001.json this command ,but the json file is null,
![image](https://user-images.githubusercontent.com/23693269/141606082-91100d48-1f73-4d77-9795-5a35df778cb9.png)

you doc is
![image](https://user-images.githubusercontent.com/23693269/141606094-431f4560-f11f-405b-b52d-ced6d44decd6.png)

I still don't know what U is

**Comment by tkeskita** [comment]
Your data is of type vtkImageData, you can connect Info node directly to VTK To OpenVDB exporter. Your data array name seems to be `MetaImage`, which you can export e.g. in `Density File Name`.

To see full node tree for OpenVDB export example, go to Tree Tab -> Examples -> cubeflow_openvdb_export. U is velocity vector in the example.

**Comment by Molers** [comment]
I see ,Thank you for your reply
