### ISSUE TITLE
Time Selector not working?

### ISSUE THREAD

**Issue by AhmedSalih3d** [tkeskita/BVtkNodes#7]
Thanks for making this package available for 2.80 first and foremost.

Secondly, I have about 200 vtk files, which I want to load in at current time step, in the blender time line. I load the data file correctly and it works;

![image](https://user-images.githubusercontent.com/36305327/75226000-e0c12580-57ab-11ea-8eb3-5327f8e7546a.png)

Is it possible to do what I want to do, to read files depending on time step?

Kind regards

**Comment by tkeskita** [comment]
Hello,

I have not tried to read vtk files as time series yet, I don't know. Might depend on which reader is used. Can you provide e.g. 3 first vtk files for some small test case?

**Comment by AhmedSalih3d** [comment]
Of course!

Just change the file extension, back to "vtk". It is is a particle simulation, so these three time steps will look quite  similar, since they are from a 800 time steps simulation. 

Hope you can get it to work

[PartFluid_0001.txt](https://github.com/tkeskita/BVtkNodes/files/4260400/PartFluid_0001.txt)
[PartFluid_0002.txt](https://github.com/tkeskita/BVtkNodes/files/4260401/PartFluid_0002.txt)
[PartFluid_0000.txt](https://github.com/tkeskita/BVtkNodes/files/4260402/PartFluid_0000.txt)

Kind regards

**Comment by tkeskita** [comment]
Thanks! I was unable to find a reader for .vtk that is time aware. It seems that even [Paraview has some internal way to work around this](https://www.paraview.org/Wiki/Animating_legacy_VTK_file_series). If anyone finds one, please let me know. However, I'm thinking about making a small hack to detect frame numbers in readers' FileName attribute that could be used for updating time steps. I'll reply here if I get it to work.

**Comment by AhmedSalih3d** [comment]
Awesome! I hope you can get it to work, since it would make it so that I can use Blender for scientific vizualisations turned to "realistic renders" instead of Paraview, which can be so beneficial in some cases. I will keep posting "issues" / "suggestions", please do not be deterred by them, I am just really happy that I found this possibility.

Kind regards

**Comment by tkeskita** [comment]
Hi, I added a hack which updates time step frame number in Time Selector node's input node, so that it updates frame number in file name. You need to specify a vtk file name for the Reader node, add Time Selector right after Reader node, and after that if you change frame in Blender's time line, it should update the Reader's file name accordingly. Please load and install new version of add-on and test it!

**Comment by AhmedSalih3d** [comment]
Thanks! It works now;

![image](https://user-images.githubusercontent.com/36305327/75477760-16793080-599d-11ea-9042-7e80e3f58fe5.png)

By playing the time line one sees that the particles will move and the only reason it says "No time data on input", is just because the vtk file it self does not hold time information.

I compared with the native performance (framed per second in paraview and blender) and I see that;

Paraview: 30 FPS
Blender: 7.5 FPS

So there is still some work to do in optimization, but it is nice that it works and is so easy to do!

Kind regards

**Comment by tkeskita** [comment]
Great! You can post your results here if you wish: [https://blenderartists.org/t/bvtknodes-gallery/1161079](https://blenderartists.org/t/bvtknodes-gallery/1161079)
