### ISSUE TITLE
advice on converting polydata points to spheres?

### ISSUE THREAD

**Issue by derekeden** [tkeskita/BVtkNodes#70]
Hi there,

I'm trying to convert a vtk file containing a POLYDATA dataset, which contains only points and point data.

I've attached an example vtk file (please change .txt to .vtk)
[out_lptm.txt](https://github.com/tkeskita/BVtkNodes/files/7851621/out_lptm.txt)

What I want to do is read this vtk file, and use the x/y/z coordinates of the vertices to create spheres.

I already tried using glyphs, but because (I think) the data is only points, the glyphs end up being points as well.

See below node tree and example output:

![image](https://user-images.githubusercontent.com/36650862/149057465-ccf13ce0-69f2-49f6-bd0d-f2dbb6462daa.png)

What I'm trying to do is get spheres from these points, and ideally eventually color them by a scalar.

See below example from paraview:

![image](https://user-images.githubusercontent.com/36650862/149057540-e52aab29-e8c0-4826-96ae-cb2ea9f0f9b3.png)

I realize that there is functionality to convert to blender particles, but I was having some initial issues and know it's experimental, figure there has to be a sphere/glyph approach that works like it does in paraview.

I imagine that using the vtkSpheres node could help?

![image](https://user-images.githubusercontent.com/36650862/149058007-d6d09966-30ca-466b-b187-117d4dedd696.png)

which by the looks of it would let me instantiate multiple spheres based on xyz coords and a scalar for radius.. but I can't figure it out.

Any suggestions greatly appreciated...

**Comment by tkeskita** [comment]
Hi,

seems to work OK for me with the node setup shown in your fist image. Your data is far away from origin, so there may be an issue with Blender showing the results. I moved the data to origin, see figure. Also, you seem to using an older version of BVTKNodes (VTK To Blender node does not exist in current version any more, I used VTK To Blender Mesh node)

![image](https://user-images.githubusercontent.com/38000348/149364933-dc678771-5a22-47ef-b197-1d5ff25fff02.png)

BR,
Tuomo

**Comment by tkeskita** [comment]
Oh, you seem to have input 0 and input 1 in vtkGlyph3D connected in reverse?

**Comment by derekeden** [comment]
I have no idea why it wasn't working for me, I certainly tried every combination I could think of lol, but of course as soon as I ask someone about it, it works :) Thanks

Also regarding the newest version of BVTKNodes. I've been working with an older release (~6months old I believe). When I use the latest, I get this error when trying to make a new node tree with any reader:

![image](https://user-images.githubusercontent.com/36650862/150888197-c5b64196-7875-448b-ac14-3a1ed951b8cf.png)

I'm honestly not skilled enough to understand my issue or how to fix it, all I know is the older version works 100% but when I try the exact same steps in the latest version nothing works. It may be something I'm doing wrong but I can't figure it out.

**Comment by derekeden** [comment]
Just to close this thread out, I'll post my final node tree if it helps anyone. Both "VTK to Blender" and "VTK to Blender Mesh" output nodes work in the version I have. Still having issues with latest version, but not related to this issue.

The below nodetree takes a polydata file of points with point data, it creates sphere sources at each point and also scales the size of the glyphs using an arbitrary scalar by means of the assign attribute node.

![image](https://user-images.githubusercontent.com/36650862/150896520-fcf8b9eb-e9db-4020-b5c7-30e1fbfd23d6.png)

**Comment by tkeskita** [comment]
> When I use the latest, I get this error when trying to make a new node tree with any reader:

You likely have Update Mode property (located in the Inspect Panel) set to Update All Automatically, so the error comes from File Name being initially "None".

I need to look into this, but the default value "None" for the text fields is probably a bug (should be "") in the generation routine.

BR,
Tuomo
