### ISSUE TITLE
VTK to Blender Mesh Auto Update

### ISSUE THREAD

**Issue by Silverwing747** [tkeskita/BVtkNodes#72]
Hello,

I am wondering what happens to the auto-update option in the VTK to Blender Mesh node? This option existed in the tutorial screenshots, but now it's gone. Currently, for every time frame, I have to manually update the VTK node, which is very inconvient. 

Currently, I am using VTK 9.1.0 with Blender 2.93.

Figure1: current VTK to Blender Mesh node
![image](https://user-images.githubusercontent.com/57307641/149848855-f6c5251e-8384-431e-bccc-88961b877147.png)

Figure2: VTK to Blender Mesh node in the tutorial
![image](https://user-images.githubusercontent.com/57307641/149848988-58ce208d-7b1d-4383-846c-915bf45b50c5.png)

**Comment by Silverwing747** [comment]
Hi Tuomo,

Thank you for this quick reply. Also thank you for writing this amazing add-on :)

I checked the inspect panel, however, it seems to be empty.
![image](https://user-images.githubusercontent.com/57307641/149967831-35014076-03ce-483c-b7b2-d224206ffb24.png)

I also take a look at the code. I found that if I comment out line 277 for def on_frame_change in the __init__.py file, the vtk object will automatically update with time. So I am a little curious. Am I not doing things properly, or those lines are supposed to be commented out?
![Screen Shot 2022-01-18 at 10 34 37](https://user-images.githubusercontent.com/57307641/149968416-d049643c-2e24-4f7f-bade-8a70e33cfbd4.png)

**Comment by tkeskita** [comment]
Hi,

Inspect Panel showing as empty suggests you are not maybe using latest version of BVTKNodes? Can you try to update according to instructions in docs?

Next, try to load Tree Panel -> Examples -> `cubeflow_cut_plane` and see if that works for you, with Update Mode changed to Update All Automatically?

Code seems correct, it's supposed to run update on line 300.

**Comment by Silverwing747** [comment]
Hi Tuomo,

I am using the latest version (0.8) along with vtk9.1.0 and blender 2.93. I tested on both windows and Mac, and I still don’t see such option under inspect panel. Could tell what’s the setting you are using?

**Comment by tkeskita** [comment]
I'm on Linux with Ubuntu 20.04, BVTKNodes latest commit acfbb7dcea916330eded035d7a40713525f36e47 (=0.8) and Blender 2.93.6, and tested previously also with Blender 3.0.0. I can make a test on Windows in a few days.

Please check that the add-on version number and path to add-on is what you expect in Blender -> Preferences -> Add-ons -> BVTKNodes

If you start Blender from command line, does it show any error messages?

**Comment by Silverwing747** [comment]
I checked the add-on version and path in Blender. It indeed shows version 0.8. 

Also, there is no error at all when I start blender from the command line. 

I will try both Blender 2.93.6 and Blender 3.0.0

<img width="660" alt="Screen Shot 2022-01-19 at 10 42 50" src="https://user-images.githubusercontent.com/57307641/150164958-34f50e82-9819-451c-a934-7d82d1d6d389.png">

**Comment by tkeskita** [comment]
Can you try to disable the addon, rename the folder in that path from `BVtkNodes-master` to `BVtkNodes`, then enable the addon?

**Comment by Silverwing747** [comment]
It works! Thank you so much for the help. Do you know what's the potential reason behind it?

![image](https://user-images.githubusercontent.com/57307641/150199206-288adc99-0b19-4377-907e-faa1b3241225.png)

**Comment by tkeskita** [comment]
OK good to know that it works! Looks like Python has trouble finding module BVtkNodes when doing `from BVtkNodes import ...` if the root folder is not named exactly like so. I consider this is a bug, I'll find a way to fix it or implement a workaround, thanks!
