### ISSUE TITLE
VTK to blender mesh: faces.new(...): sequence incorrect size

### ISSUE THREAD

**Issue by lzhshou** [tkeskita/BVtkNodes#73]
Hi Keskitalo,

Thank you for the efforts in maintaining this great and useful tool.

I encountered the error of sequence incorrect size prompted by the facets.new() function, when trying to import vtk data to blender mesh using the VTK to blender mesh node (the bottom figure). The file is prepared in polydata format with triangle strips, and it works well in paraview (the top figure). 

Would you please help take a look at this issue? (The vtk file is attached as particle_000_000000000040000.zip)

Many thanks,

Zhengshou

![vtk_paraview](https://user-images.githubusercontent.com/11776407/150639687-a366ff0f-3ce3-4d35-a358-eadcfd09e3ef.jpeg) 

![blender_vtk_issue](https://user-images.githubusercontent.com/11776407/150639499-1dad1bf4-f1e0-414b-b626-d3e005d6407a.png)

[particle_000_000000000040000.zip](https://github.com/tkeskita/BVtkNodes/files/7918375/particle_000_000000000040000.zip)

**Comment by tkeskita** [comment]
Hi,
thanks for providing data example for this issue! There is something strange in the triangle strip VTK data which causes troubles. I'll check it, but meanwhile you can add `vtkTriangleFilter` after reader as a workaround, if surface data is enough for you.

**Comment by lzhshou** [comment]
Hi Keskitalo,

Thanks for the quick reply. I have tried ``vtkTriangleFilter``, but the issue is still there.

FYI, here is the snippet code to create the triangle strips. Please let me know if there is anything else I can help with this issue.

VecXT<int> triangle_strips;
  for (auto &tmp_facet : facets) {
    triangle_strips.emplace_back(tmp_facet[0]);
    triangle_strips.emplace_back(tmp_facet[0]);
    triangle_strips.emplace_back(tmp_facet[1]);
    triangle_strips.emplace_back(tmp_facet[2]);
    triangle_strips.emplace_back(tmp_facet[2]);
  }

Again, thanks for your help.

**Comment by tkeskita** [comment]
Sorry my mistake. I just committed a "hot fix", with that it should not crash any more, although you still need vtkTriangleFilter.

**Comment by lzhshou** [comment]
I checked out the new commit and it works. Thanks.

**Comment by tkeskita** [comment]
FYI Your triangle strip data seems not to be aligned with formulation of [VTK triangle strips](https://kitware.github.io/vtk-examples/site/Cxx/GeometricObjects/TriangleStrip/), since not all sets of three points define a triangle. But it seems that by using `vtkTriangleFilter` the end product contains all the faces you need. I've slightly modified the hot fix from yesterday, should not affect the end result.

**Comment by lzhshou** [comment]
You are right that I did not implement an exact triangle strip algorithm, and just used that workaround in my code. Thanks for the follow-up.
