### ISSUE TITLE
Exporting Blender object to vtk?

### ISSUE THREAD

**Issue by AhmedSalih3d** [tkeskita/BVtkNodes#8]
Hello!

I cannot see why this should not be possible, so that is why I am making this issue. Using a vtk sphere source, I have drawn on the left this bowl shape and I am able to export it to vtk, if I remove the option of "tooutputstring" (I don't know what it does). On the right hand side I have now applied a solidify modifer in Blender and I wish to export this object to vtk - how do I go about doing that? I cannot see any reason why it should not be possible - specifically I am trying to use the "polydata" vtk writer.

![image](https://user-images.githubusercontent.com/36305327/75441492-0db53a00-595e-11ea-9cf8-7a3b9437305c.png)

Kind regards

**Comment by tkeskita** [comment]
Hi, BVTKNodes does not currently have a "BlenderToVTK" feature. Instead, you can try my other add-on [io-mesh-vtk](https://github.com/tkeskita/io_mesh_vtk) or another similar add-on which can export blender mesh into VTK polydata format.
