### ISSUE TITLE
vtkContourFilter is not better than before

### ISSUE THREAD

**Issue by brioglade** [tkeskita/BVtkNodes#87]
vtkContourFilter can not add Contour values arbitrarily now.

**Comment by tkeskita** [comment]
Hi, what do you mean? Please have a look at cubeflow_contours example tree.

**Comment by brioglade** [comment]
![image](https://user-images.githubusercontent.com/13229692/168427454-2db301e6-8c04-4444-b4f9-59dd15662983.png)
This is the node before that I can press the + to add what I want.
The latest update version can't do that as following.
![image](https://user-images.githubusercontent.com/13229692/168427814-1804816f-c6c1-4b0f-930a-7078699f5660.png)
Or what I was missing?

**Comment by tkeskita** [comment]
Hi, yes the way you specify several contour values has changed. In new version you put "-0.9" to Single Value, and "0.0, 0.1" to Additional Values.
