### ISSUE TITLE
Feature Request: TTK Support

### ISSUE THREAD

**Issue by JonasLukasczyk** [tkeskita/BVtkNodes#89]
Hi everyone,
I'm a senior developer of the [Topology ToolKit (TTK)](https://github.com/topology-tool-kit/ttk) and I'm wondering how complex it would be to get TTK filters to work with BVtkNodes. To oversimplify: TTK is basically a collection of additional VTK filters which can even be accessed through python (using VTK's python binding mechanism). It is possible to install ttk via anaconda, but unfortunately not via pip.  Can you give me some pointers on how that could be achieved? An analogous question would be on how to integrate a homegrown VTK filter written in C++ which is not part of the VTK repository but uses VTK as a library.

Best
Jonas

**Comment by tkeskita** [comment]
Hi,

I'm not sure. The idea of BVTKNodes is that it allows VTK objects to be handled from the Blender Node tree via Python. The VTK elevation filter is a simple example, here's the [automatically generated code for the node class](https://github.com/tkeskita/BVtkNodes/blob/master/generated_nodes/gen_VTKFilters1.py#L1944). I think if you have a Python class which inherits from vtkAlgorithm you might be able to bind it to BVTKNodes in similar fashion, and maybe it works like any other filter in the pipeline? You can test it if you add such a class definition to e.g. file custom_nodes/VTKFilters.py. There you'll also find more examples of customized nodes.

Another alternative might be to add the Python code to [Custom Filter Node](https://bvtknodes.readthedocs.io/en/latest/BVTKNodes.html#python-interaction-and-custom-filter), but that code is currently run quite often in Blender, so it may be very slow to use.

BR,
Tuomo

**Comment by JonasLukasczyk** [comment]
Thank you, that is helpful!

It would be perfect if we could auto-generate the nodes for the ttk filters in the same way it is currently done for VTK filters. How do you determine the python classes (vtk filters) that are going to be processed? Could we simply add the ttk filters to that list either manually or instruct BVTKNodes to search the ttk python namespace for ttk filters (all of them inherit from vtkAlgorithm)?

Best
Jonas

**Comment by tkeskita** [comment]
Hello,

yes, you could modify the code parsing of vtk classes (see files in generate folder: populate_db.py and vtk_info.py, finally generate.py creates the files in generated_nodes folder from the db). The parsing heuristics is layed out in vtk_info.py. It's not perfect but it goes so far it works for most VTK classes (thanks to the original developer who did this!).

**Comment by tkeskita** [comment]
Hi,

yes setting up arrays to process is not trivial. For this purpose there is the [Custom Code](https://bvtknodes.readthedocs.io/en/latest/BVTKNodes.html#addition-of-custom-code-to-vtk-nodes) capability to work around this issue. But it is not super convenient. Some single nodes have been manually customized to be user friendly, but vast majority stand as-is-generated. Already now upgrading the custom nodes when VTK changes happen is a burden, so manual fixes is not a good solution in the long run.

I'm not familiar with how Paraview works internally, maybe that kind of processing would work.

Aside: One of the issues I have with Paraview is that it assumes I want to "process nth field", while what I really would like it to do is "process field named velocity". This is an issue when field numbering changes e.g. between time steps, or when you want to pre-define the field to be processed prior to knowing which fields are available. Therefore I've made some custom nodes to require explicit field names.
