### ISSUE TITLE
colormap with opacity

### ISSUE THREAD

**Issue by argapost** [tkeskita/BVtkNodes#97]
Hi! First of all, thank you for this amazing plugin!

I wondered is it possible to add an opacity transfer function to a colormap? (similar to paraview) I want to make a 2D slice and make some colors transparent. Similar to the following picture:

![image](https://github.com/tkeskita/BVtkNodes/assets/58076098/9cd7983c-ecdb-41c5-831e-4682e6c8ee17)

Thank you in advance!

**Comment by tkeskita** [comment]
Hi,
yes you can change alpha value for color points in the Color Ramp node.
