### ISSUE TITLE
colormapper negative values not colored correclty

### ISSUE THREAD

**Issue by argapost** [tkeskita/BVtkNodes#99]
Hi again,

I try to put a custom range to my scalar from -5 to 5 and map the colours blue to red, as seen below:
![blender_screenshot](https://github.com/tkeskita/BVtkNodes/assets/58076098/b249da70-388a-4dde-85c8-869f8a0f40e0)

But I get the following result:
![blender_2](https://github.com/tkeskita/BVtkNodes/assets/58076098/95054a2b-4b16-4ba4-990b-4f360ed26166)

Whereas in Paraview I get:
![paraview](https://github.com/tkeskita/BVtkNodes/assets/58076098/c5090317-9c8c-43cf-9e74-d0e56328b155)

Do I do something wrong?

Thank you in advance!

**Comment by tkeskita** [comment]
Hi, does it help if you disable "GenerateCutScalars" on the vtkCutter node?

**Comment by tkeskita** [comment]
OK, thanks for testing and reporting! It seems that there is a bug, which turns negative data values into positive, I'll look into it.

**Comment by tkeskita** [comment]
Hi, I found and fixed a bug, can you please upgrade and try to see is it fixed for you? Thanks!

**Comment by argapost** [comment]
Hi, yes, it works! Thank you very much for your quick fix!

P.S. If I want to set the position and the colours of the colour ramp programmatically with blender python script or custom code, how would you suggest doing it?

**Comment by tkeskita** [comment]
Hi,
great! Custom Code can't be used for editing color ramp elements. For that, you need to modify  `bpy.data.textures[your_texture_name].color_ramp.elements`. See [colormap.py](https://github.com/tkeskita/BVtkNodes/blob/master/colormap.py#L49-L60).

**Comment by argapost** [comment]
Perfect thanks I ll have a look!
